name: clang-tidy CI

on: [ pull_request ]

jobs:

  build-project:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler:
          - cc: clang-11
            cxx: clang++-11
    env:
      CC: clang-11
      CXX: clang++-11
      build_dir: build

    steps:
      - name: Fetch compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-11 clang++-11 clang-tidy-11
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create build directory
        run: mkdir -p ${build_dir}
      - name: Configure project
        run: cd ${build_dir} && cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
      - name: Run clang-tidy
        run: |
          run-clang-tidy-11 \
            -p=build \
            -j$(nproc) \
            -header-filter include/* \
            -export-fixes clang-tidy-fixes.yaml \
            include/CommandParser.h example_main.cpp
      - name: Run clang-tidy-pr-comments action
        uses: platisd/clang-tidy-pr-comments@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clang_tidy_fixes: clang-tidy-fixes.yaml
          request_changes: true
